const courses = [
  {
    id: 1,
    title: "Computer Science Engineering",
    description:"Computer Science Engineering is the study of computers and computational systems. It involves designing, analyzing, and developing computer software and hardware.",
    image: "https://media.tenor.com/A3qaVncurssAAAAM/kroppa-g%C4%B1f.gif",
    duration: "4 years",
    eligibility: "10+2 with Physics, Chemistry, and Mathematics",
    curriculum: [
      "Programming",
      "Data Structures and Algorithms",
      "Database Management Systems",
      "Computer Networks",
      "Operating Systems",
      "Software Engineering",
    ],
    careerOptions: [
      "Software Developer",
      "Web Developer",
      "Data Analyst",
      "Network Administrator",
      "Systems Analyst",
    ],
  },
  {
    id: 2,
    title: "Electrical Engineering",
    description: "Electrical Engineering deals with the study and application of electricity, electronics, and electromagnetism. It involves designing, developing, and maintaining electrical systems and equipment.",
    image: "https://media.tenor.com/69eSUQkTrfEAAAAM/rick-and-morty-science-fail.gif",
    duration: "4 years",
    eligibility: "10+2 with Physics, Chemistry, and Mathematics",
    curriculum: [
      "Circuit Analysis",
      "Electromagnetic Fields",
      "Power Systems",
      "Control Systems",
      "Digital Electronics",
      "Renewable Energy Systems",
    ],
    careerOptions: [
      "Electrical Engineer",
      "Power Systems Engineer",
      "Control Systems Engineer",
      "Electronics Engineer",
      "Renewable Energy Engineer",
    ],
  },
  {
    id: 3,
    title: "Mechanical Engineering",
    description: "Mechanical Engineering involves the study of design, analysis, manufacturing, and maintenance of mechanical systems. It covers a wide range of areas such as mechanics, thermodynamics, and materials science.",
    image: "https://media.tenor.com/2Q6gbynE92YAAAAM/uts-uts-engineering.gif",
    duration: "4 years",
    eligibility: "10+2 with Physics, Chemistry, and Mathematics",
    curriculum: [
      "Engineering Mechanics",
      "Thermodynamics",
      "Fluid Mechanics",
      "Machine Design",
      "Heat Transfer",
      "Manufacturing Processes",
    ],
    careerOptions: [
      "Mechanical Engineer",
      "Automotive Engineer",
      "Aerospace Engineer",
      "Manufacturing Engineer",
      "Energy Engineer",
    ],
  },
  {
    id: 4,
    title: "Information Technology",
    description: "IT Engineering deals with the study and application of electricity, electronics, and electromagnetism. It involves designing, developing, and maintaining electrical systems and equipment.",
    image: "https://media.tenor.com/qoDOnF_uBYIAAAAM/office-motion-graphics.gif",
    duration: "4 years",
    eligibility: "10+2 with Physics, Chemistry, and Mathematics",
    curriculum: [
      "Circuit Analysis",
      "Electromagnetic Fields",
      "Power Systems",
      "Control Systems",
      "Digital Electronics",
      "Renewable Energy Systems",
    ],
    careerOptions: [
      "Electrical Engineer",
      "Power Systems Engineer",
      "Control Systems Engineer",
      "Electronics Engineer",
      "Renewable Energy Engineer",
    ],
  },
  {
    id: 5,
    title: "Civil Engineering",
    description: "Civil Engineering deals with the study and application of electricity, electronics, and electromagnetism. It involves designing, developing, and maintaining electrical systems and equipment.",
    image: "https://media.tenor.com/-o-fUO-IpawAAAAM/bumping-into-your-ex-after-several-years-dhanush-nodding.gif",
    duration: "4 years",
    eligibility: "10+2 with Physics, Chemistry, and Mathematics",
    curriculum: [
      "Circuit Analysis",
      "Electromagnetic Fields",
      "Power Systems",
      "Control Systems",
      "Digital Electronics",
      "Renewable Energy Systems",
    ],
    careerOptions: [
      "Electrical Engineer",
      "Power Systems Engineer",
      "Control Systems Engineer",
      "Electronics Engineer",
      "Renewable Energy Engineer",
    ],
  },
];

export default courses;